.\" Manpage for QText
.\" Contact jmedved@jmedved.com to correct errors or typos.
.TH QTEXT 1 "28 Dec 2019" "MAJOR.MINOR" "qtext man page"


.SH NAME

QText \- Note taking utility


.SH SYNOPSIS

.ad l
\fBqtext\fR


.SH DESCRIPTION
Note taking application with auto-save.


.SH SHORTCUTS

.TP 12
\fBCtrl+C\fR
Copy text

.TP
\fBCtrl+G\fR
Find folder or file by name

.TP
\fBCtrl+N\fR
New file

.TP
\fBCtrl+O\fR
Select folder

.TP
\fBCtrl+R\fR
Reload file

.TP
\fBCtrl+S\fR
Save file immediatelly

.TP
\fBCtrl+V\fR
Paste text

.TP
\fBCtrl+X\fR
Cut text

.TP
\fBCtrl+Y\fR
Redo action

.TP
\fBCtrl+Z\fR
Undo action

.TP
\fBAlt+1\fR
Select first tab

.TP
\fBAlt+2\fR
Select second tab

.TP
\fBAlt+3\fR
Select third tab

.TP
\fBAlt+4\fR
Select fourth tab

.TP
\fBAlt+5\fR
Select fifth tab

.TP
\fBAlt+6\fR
Select sixth tab

.TP
\fBAlt+7\fR
Select seventh tab

.TP
\fBAlt+8\fR
Select eight tab

.TP
\fBAlt+9\fR
Select nineth tab

.TP
\fBAlt+0\fR
Select tenth tab

.TP
\fBAlt+Left\fR
Select file to the left

.TP
\fBAlt+Right\fR
Select file to the right

.TP
\fBAlt+Up\fR
Select previous folder

.TP
\fBAlt+Down\fR
Select next folder

.TP
\fBF2\fR
Rename file


.SH AUTHOR

Josip Medved <jmedved@jmedved.com>
